# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  # Forward port 80 on the VM to port 8080 on our local machine
  config.vm.network :forwarded_port, guest: 80, host: 8080

  # Create a private network for testing Apache
  config.vm.network "private_network", ip: "192.168.33.10"
end
