# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  # Uncomment if local installation from USB stick is required
  #config.vm.box_url = "https://atlas.hashicorp.com/ubuntu/boxes/trusty64/versions/20160222.0.0/providers/virtualbox.box"

  # Forward port 80 on the VM to port 8080 on our local machine
  config.vm.network :forwarded_port, guest: 80, host: 8080

  # Create a private network for testing Apache
  config.vm.network "private_network", ip: "203.0.113.5"

  # config.vm.provider "virtualbox" do |vb|
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
end
